apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
  namespace: myns
spec:
  volumes:
  - name: truststore-jks
    secret:
      secretName: truststore.jks
  containers:
  - image: quay.io/wildfly/wildfly
    name: mypod
    volumeMounts:
    - name: truststore-jks
      readOnly: true
      mountPath: "/tmp/certs"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
